create table patients (
     id int not null auto_increment primary key,
     visit_reason text not null,
     symptoms text not null,
     has_insurance varchar(4),
     has_allergies varchar(4),
     allergies text,
     medical_conditions varchar(255),
     medications varchar(255),
     had_surgeries varchar(4),
     surgeries varchar(255),
     insurance varchar(255),
     fam_disease varchar(8),
     fam_diseases text,
     use_tobacco varchar(4),
     tobacco_usage varchar(255),
     drink_alcohol varchar(4),
     alcohol_usage varchar(255),
     use_drugs varchar(4),
     drug_usage varchar(255),
     pt_consent varchar(4),
     spiritual_beliefs varchar(4),
     what_spiritual_beliefs varchar(255),
     symptoms_before varchar(4),
     self_harm varchar(4),
     fname varchar(24) not null,
     lname varchar(36) not null,
     street_address varchar(48),
     home_city varchar(48),
     home_state varchar(48),
     home_zip int(9),
     pt_phone int(10),
     email varchar(255),
     pt_dob int(8),
     pt_notes text
     ) engine = innodb;
     
create table int_users (
     id int not null auto_increment primary key,
     username varchar(128) not null,
     fname varchar(24) not null,
     lname varchar(48) not null,
     emp_id varchar(24) not null,
     password varchar(255) not null,
     google2fa_secret varchar(32),
     role varchar(16) not null default 'user',
     status varchar(16) not null default 'active',
     timezone varchar(8) not null,
     phone varchar(15),
     email varchar(255) not null,
     office varchar(64),
     office_add varchar(128),
     office_city varchar(48),
     office_state varchar(48),
     office_zip int,
     created_on timestamp default current_timestamp,
     created_by varchar(255),
     updated_on timestamp,
     updated_by varchar(255)
     )engine=innodb;
